#!/usr/bin/perl

$perlpath = "/usr/bin/perl";
$passfile = "/home/sites/site2/users/nemo/web/mail/pass";
$memberinfo = "/home/sites/site2/users/nemo/web/mail/info";
$trackdir = "/home/sites/site2/users/nemo/web/mail/trackdir";
$tempdir = "/home/sites/site2/users/nemo/web/mail/tempdir";
$maildir = "/home/sites/site2/users/nemo/web/mail/maildir";
$lists = "/home/sites/site2/users/nemo/web/mail/lists";
$graphics = "/home/sites/site2/users/nemo/web/mail/graphics";
$mailprog = "/usr/sbin/sendmail";
$LOCK_EX = "2";
$websiteurl = "http://www.nemohackers.com";
$os = "unix";
$mailusing = "sendmail";
$smtp_addr = "mail.yourserver.com";
$cgipath = "/home/sites/site2/users/nemo/web/mail";
$extension = "pl";
$information = "/home/sites/site2/users/nemo/web/mail";
$notification = "ON";
$config_session = "1800";
$permissions = "0755";

$ready = "1";

1;