<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 TRANSITIONAL//EN">

<HTML>

<HEAD>

<TITLE>[ nemo hackers ]</TITLE>

<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1" CHARSET="iso-8859-1">

<META NAME="keywords" CONTENT=

"newbie, newbies, newbiesplace, newbiezplace, learn to hack, how to hack, how do i hack,hack hotmail, hacking hotmail, hack yahoo, hacking yahoo, hacking tools, hacking programs, hacking site, newby, newbeisplace, newbeizplace,">

<META NAME="description" CONTENT="NewbiezPlace.com - Where newbies come to learn the art of hacking. This site is a vast resource for hacking methodology and toolz">

<META NAME="robots" CONTENT="FOLLOW,INDEX">





    <?php require('header.php'); ?>







<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="5" CELLSPACING="0" WIDTH="750"><TR>

<TD BGCOLOR="#000000" VALIGN="top" WIDTH="160">
<!-- corners -->

<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="160">

<TR BGCOLOR=""><TD>
<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="160">
<TR>
<TD WIDTH=3><IMG SRC="./images/tleftblue1agif.gif" BORDER=0></TD>
<TD BGCOLOR="#024070" WIDTH="154">
<CENTER><CENTER><b>Menu</b></CENTER></CENTER></TD>
<TD WIDTH=3><IMG SRC="./images/trightblue1agif.gif" BORDER=0></TD>
</TR>
</TABLE>
</TR>



<TR BGCOLOR="#1c1f22">

<TD WIDTH="160" BGCOLOR="#1c1f22" CELLPADDING="2">

<TABLE BORDER="0" CELLPADDING="4" CELLSPACING="0" WIDTH="100%">

<TR CLASS="small">

<TD BGCOLOR="#1C1F22" HEIGHT="426" VALIGN="top">

<CENTER>

    <?php require('menu.php'); ?>

</CENTER>











</TD></TR></TABLE>
<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/bleftdgrey1agif.gif" BORDER=0></TD>
<TD WIDTH="754" BGCOLOR="1C1F22">
<TD WIDTH=3><IMG SRC="./images/brightdgrey1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

</TD></TR></TABLE></TD>

<!------------eend left column--------------->

<!------------rright column--------------->

<TD BGCOLOR="#000000" VALIGN="top">

<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="100%">

<TR VALIGN="top"><TD BGCOLOR="#000000">

<!------------------11111111111111111111111111------------------>


<TABLE bgColor=#000000 border=0 cellPadding=0 cellSpacing=1 width="100%" height="170">



<TR bgColor=#000000><TD bgcolor="#000000" height="16">


<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/tleftblue1agif.gif" BORDER=0></TD>
<TD BGCOLOR="#024070" WIDTH="754">
<CENTER><B>Text Archives</B></CENTER></TD>
<TD WIDTH=3><IMG SRC="./images/trightblue1agif.gif" BORDER=0></TD>
</TR>
</TABLE>



</TD></TR>



<TR bgColor=#24252f>



<TD height="150">







<TABLE border=0 cellPadding=4 cellSpacing=0 width="100%">



<TR class=small><TD bgcolor="#1C1F22">


	  
<TABLE WIDTH="100%">
<TR>

  <TD WIDTH="15"><!-- Margin --></TD>

<TD>
		  <FONT face="Verdana, Helvetica" color="white" size="2">
<br>

		                 <FONT face="Verdana, Helvetica" color="white" size="2">
		  <?php include('dir.php');?>
		  
		  </TD>
                             <td width=15><!---shit-----></td>
</TR>
</TABLE>



  </TD></TR></TABLE>

  <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/bleftdgrey1agif.gif" BORDER=0></TD>
<TD WIDTH="754" BGCOLOR="1C1F22">
<TD WIDTH=3><IMG SRC="./images/brightdgrey1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

  </TD></TR></TABLE>



  </TD></TR></TABLE>



<FONT class=small face="Arial"><BR></FONT>











            



<!----------------333333333333333333333333------------------><!----------------4444444444444444444444------------------>					



			

















</TD></TR></TABLE>


</TD></TR></TABLE></TD></TR></TABLE>



<TABLE bgColor=#000000 border=0 cellPadding=0 cellSpacing=0 width=750 height=2>



<TR bgcolor="#024070" height=2><TD bgcolor="#024070" height=2></TD></tr></TABLE>



    <?php require('footer.php'); ?>









</BODY></HTML>



