    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 TRANSITIONAL//EN">
<HTML>
<HEAD>
<TITLE>[ nemo hackers ]</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1" CHARSET="iso-8859-1">
<META NAME="keywords" CONTENT=
"newbie, newbies, newbiesplace, newbiezplace, learn to hack, how to hack, how do i hack,hack hotmail, hacking hotmail, hack yahoo, hacking yahoo, hacking tools, hacking programs, hacking site, newby, newbeisplace, newbeizplace,">
<META NAME="description" CONTENT="NewbiezPlace.com - Where newbies come to learn the art of hacking. This site is a vast resource for hacking methodology and toolz">
<META NAME="robots" CONTENT="FOLLOW,INDEX">


    <?php require('header.php'); ?>


<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="5" CELLSPACING="0" WIDTH="750"><TR>
<TD BGCOLOR="#000000" VALIGN="top" WIDTH="160">
<TABLE BGCOLOR="#1c1f22" BORDER="0" CELLPADDING="2" CELLSPACING="1" WIDTH="160">
<TR BGCOLOR="#515468"><TD BGCOLOR="#024070" WIDTH="160">
<CENTER><CENTER CLASS="small_uppercase"><b>Menu</b></CENTER></CENTER>
</TD></TR>
<TR BGCOLOR="#1c1f22">
<TD WIDTH="160" BGCOLOR="#1c1f22" CELLPADDING="2">
<TABLE BORDER="0" CELLPADDING="4" CELLSPACING="0" WIDTH="100%">
<TR CLASS="small">
<TD BGCOLOR="#1C1F22" HEIGHT="426" VALIGN="top">
<CENTER>
    <?php require('menu.php'); ?>
</CENTER>




</TD></TR></TABLE></TD></TR></TABLE>



</TD>



<!------------end left column--------------->







<!------------right column--------------->



<TD BGCOLOR=#000000 VALIGN=top>

<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH="100%">

<TR VALIGN=top><TD BGCOLOR="#000000">









<!------------------11111111111111111111111111------------------>











<TABLE BGCOLOR=#1c1f22 BORDER=0 CELLPADDING=0 CELLSPACING=1 WIDTH="100%">

<TR BGCOLOR=#515468><TD BGCOLOR="#024070">

<CENTER CLASS=small_uppercase><SPAN CLASS=small>
<b>Defaced</b>
</center>
</TD></TR>

<TR BGCOLOR=#24252f>

<TD>

<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=0 WIDTH="100%">

<TR CLASS=small><TD BGCOLOR="#1C1F22">

 <CENTER>


         <FONT face="Verdana, Helvetica" color="white" size="2"><B>
					 <FONT face="Verdana, Helvetica" color="white" size="2">

					  As admins of Nemohackers we are responcible for our own actions but we are NOT responcible for yours!! Sites that are added to this list by non Admins are not condoned by use niether do we clmaim responciblty for your actions!
<br>
<br>

<a href="disclaimer.php">Disclaimer</a>

<br>
<br></B><br> <FONT face="Verdana, Helvetica" color="white" size="2">

 <FONT face="Verdana, Helvetica" color="white" size="0">
 <?php require("defaced/defaced.php");?>
 </font>
 <br>
 <br>


<!-- post new form -->
<center>
<table border=0 width=70%>
<form method=post action=defaced/defaced.php>
<tr>
<td><p><b> <FONT face="Verdana, Helvetica" color="white" size="2">Name:</td>
<td><input type=text name=name size=10 maxlength=20 style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1"></b></p></td>
</tr>

<tr>
<td><p><b> <FONT face="Verdana, Helvetica" color="white" size="2">Email:</td>
<td><input type=text name=email size=10 maxlength=20 style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1"></p></td>
</tr>

<tr>
<td><p><b> <FONT face="Verdana, Helvetica" color="white" size="2">Defaced URL:</td>
<td><input type=text name=url size=10 maxlength=50 style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1"></p></td>
</tr>
</table>
<input type=hidden name=mode value=1>
<input type=submit value=Add!  style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1">
</form>
</center>


                      <BR>                      </FONT>


</TD></TR></TABLE></TD></TR></TABLE></TD></TR></TABLE></TD></TR></TABLE>

</TD></TR></TABLE></TD></TR></TABLE>

<TABLE BGCOLOR=#000000 BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=750 HEIGHT=2>

<TR BGCOLOR="#024070" HEIGHT=2><TD BGCOLOR="#024070" HEIGHT=2></TD></TR></TABLE>

    <?php require('footer.php'); ?>

<BR>


