<div class="arch">
<center>
<TABLE width=100% cellpadding=3 cellspacing=0 border=0 class="arch"><TR> <TD valign=top width=100% colspan=3> <center>


                   <FONT face="Verdana, Helvetica" size="2">

   Welcome to the text archives. You can use the alphabet below to jump to the appropriate area.
   Please upload texts from <a href="uploader.php3">Upload Section</a>.<br><br>
   

<center>
<table width=400 cellpadding=5><tr><td width=25%>

<form method=post action=search.php>
     <FONT face="Verdana, Helvetica" size="2">
Search For :<br><input size="15" type=text name=find style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1""> <br>
     </td>     <td width=30%>     <FONT face="Verdana, Helvetica" size="2">
Results Per Page :<br>

<SELECT name="rpp" style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1">

<option value="10">10</option>

<option value="15">15</option>

<option value="20">20</option>

<option value="25">25</option>

<option value="50">50</option>

<option value="100">100</option>

<option value="10000000000">All</option>

</SELECT>         <br>  </td>   </tr><tr>  <td width=25%>



  <FONT face="Verdana, Helvetica" size="2">
                                  

<input type=submit value="Search!" style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1">


 </td>     <td width=20%>  
 
                           <FONT face="Verdana, Helvetica" size="2">

Search Depth: <br>

<SELECT  style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1" name="sdep">

<option value="100">100</option>

<option value="150">150</option>

<option value="200">200</option>

<option value="250">250</option>

<option value="500" selected>500</option>

<option value="1000">1000</option>

<option value="2000">2000</option>

<option value="5000">5000</option>

<option value="all">Max</option>

</SELECT>     
</form>
</td></tr></table>
</center>

  </td></tr><tr> <TD valign=top width=100% colspan=3> <center>
<a href="#01"><FONT face="Verdana, Helvetica" size="1">0</a> |
<a href="#11"><FONT face="Verdana, Helvetica" size="1">1</a> |
<a href="#21"><FONT face="Verdana, Helvetica" size="1">2</a> |
<a href="#31"><FONT face="Verdana, Helvetica" size="1">3</a> |
<a href="#41"><FONT face="Verdana, Helvetica" size="1">4</a> |
<a href="#51"><FONT face="Verdana, Helvetica" size="1">5</a> |
<a href="#61"><FONT face="Verdana, Helvetica" size="1">6</a> |
<a href="#71"><FONT face="Verdana, Helvetica" size="1">7</a> |
<a href="#81"><FONT face="Verdana, Helvetica" size="1">8</a> |
<a href="#91"><FONT face="Verdana, Helvetica" size="1">9</a> <br>    <br>
<a href="#a1"><FONT face="Verdana, Helvetica" size="1">A</a> |
<a href="#b1"><FONT face="Verdana, Helvetica" size="1">B</a> |
<a href="#c1"><FONT face="Verdana, Helvetica" size="1">C</a> |
<a href="#d1"><FONT face="Verdana, Helvetica" size="1">D</a> |
<a href="#e1"><FONT face="Verdana, Helvetica" size="1">E</a> |
<a href="#f1"><FONT face="Verdana, Helvetica" size="1">F</a> |
<a href="#g1"><FONT face="Verdana, Helvetica" size="1">G</a> |
<a href="#h1"><FONT face="Verdana, Helvetica" size="1">H</a> |
<a href="#i1"><FONT face="Verdana, Helvetica" size="1">I</a> |
<a href="#j1"><FONT face="Verdana, Helvetica" size="1">J</a> |
<a href="#k1"><FONT face="Verdana, Helvetica" size="1">K</a> |
<a href="#l1"><FONT face="Verdana, Helvetica" size="1">L</a> |
<a href="#m1"><FONT face="Verdana, Helvetica" size="1">M</a> |
<a href="#n1"><FONT face="Verdana, Helvetica" size="1">N</a> |
<a href="#o1"><FONT face="Verdana, Helvetica" size="1">O</a> |
<a href="#p1"><FONT face="Verdana, Helvetica" size="1">P</a> |
<a href="#q1"><FONT face="Verdana, Helvetica" size="1">Q</a> |
<a href="#r1"><FONT face="Verdana, Helvetica" size="1">R</a> <br>
<a href="#s1"><FONT face="Verdana, Helvetica" size="1">S</a> |
<a href="#t1"><FONT face="Verdana, Helvetica" size="1">T</a> |
<a href="#u1"><FONT face="Verdana, Helvetica" size="1">U</a> |
<a href="#v1"><FONT face="Verdana, Helvetica" size="1">V</a> |
<a href="#w1"><FONT face="Verdana, Helvetica" size="1">W</a> |
<a href="#x1"><FONT face="Verdana, Helvetica" size="1">X</a> |
<a href="#y1"><FONT face="Verdana, Helvetica" size="1">Y</a> |
<a href="#z1"><FONT face="Verdana, Helvetica" size="1">Z</a>   <br><br> </center>
</TD></TR>

<TD valign=top width=60%><b>
<FONT face="Verdana, Helvetica" color="white" size="2">Filename</B></TD><TD valign=top width=20%><B>
<FONT face="Verdana, Helvetica" color="white" size="2">Size</B></TD><TD valign=top width=20%><B>
<FONT face="Verdana, Helvetica" color="white" size="2">Date</B></TD></TR>
<?php
$shit = `ls arch`;
$shit = rawurlencode($shit);
$shit = eregi_replace("%0A", "þ", $shit);
$shit = explode("þ", $shit);
$num = count($shit);

for ($i=0; $i<$num-1; $i++){
$temp = $shit[$i];
$temp2 = $temp[0];
if (ucfirst($temp)!=$temp){
$temp = ucfirst($temp2).$temp."þ";
$shit[$i] = $temp;
}

}
sort($shit);
for ($i=0; $i<$num-1; $i++){

if ($shit[$i]!="" || $shit[$i]!=" "){
$temp = $shit[$i];
if ($temp[strlen($temp)-1]=="þ"){
$shit[$i] = substr($temp,1,-1);
}
$unixtime = filectime("arch/".urldecode($shit[$i]));
$date = date("m-d-Y", $unixtime);
$size = filesize("arch/".urldecode($shit[$i]));
$te = urldecode($shit[$i]);
$tee = $te[0];
$te2 = urldecode($shit[$i-1]);
$tee2 = $te2[0];

if (ucfirst($tee)!=ucfirst($tee2)){
echo "<tr><td colspan=3><FONT face=Verdana, Helvetica color=white size=2><a name=\"".ucfirst($tee)."1\"></a><b>$tee</b></font></td></tr>\n";
}

echo "<TR><TD valign=top width=60%><FONT face=Verdana, Helvetica color=white size=2><A HREF=\"http://nemo.pthunited.com/archive.php?p=$shit[$i]\">".rawurldecode($shit[$i])."</A>&nbsp;</TD><TD valign=top width=20%><FONT face=Verdana, Helvetica color=white size=2>$size</TD><TD valign=top width=20%><FONT face=Verdana, Helvetica color=white size=2>$date</td></TR>\n\n";
}
}
?>
</table>
</div>
