<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 TRANSITIONAL//EN">
<HTML>
<HEAD>
<TITLE>[ nemo hackers ]</TITLE>
<?php require('meta.php'); ?>
<?php require('header.php'); ?>


<!--start the individual page-->






<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="5" CELLSPACING="0" WIDTH="750"><TR>

<TD BGCOLOR="#000000" VALIGN="top" WIDTH="160">
<!-- corners -->

<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="160">

<TR BGCOLOR=""><TD>
<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="160">
<TR>
<TD WIDTH=3><IMG SRC="./images/tleftblue1agif.gif" BORDER=0></TD>
<TD BGCOLOR="#024070" WIDTH="154">
<CENTER><CENTER><b>Menu</b></CENTER></CENTER></TD>
<TD WIDTH=3><IMG SRC="./images/trightblue1agif.gif" BORDER=0></TD>
</TR>
</TABLE>
</TR>



<TR BGCOLOR="#1c1f22">

<TD WIDTH="160" BGCOLOR="#1c1f22" CELLPADDING="2">

<TABLE BORDER="0" CELLPADDING="4" CELLSPACING="0" WIDTH="100%">

<TR CLASS="small">

<TD BGCOLOR="#1c1f22" HEIGHT="426" VALIGN="top">

<CENTER>

    <?php require('menu.php'); ?>

</CENTER>











</TD></TR></TABLE>
<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/bleftdgrey1agif.gif" BORDER=0></TD>
<TD WIDTH="754" BGCOLOR="1C1F22"></TD>
<TD WIDTH=3><IMG SRC="./images/brightdgrey1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

</TD></TR></TABLE></TD>

<!------------eend left column--------------->

<!------------rright column--------------->

<TD BGCOLOR="#000000" VALIGN="top">

<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="100%">

<TR VALIGN="top"><TD BGCOLOR="#000000">


<!------------------11111111111111111111111111------------------>
<!------------------11111111111111111111111111------------------>

<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="100%">

<TR BGCOLOR="#000000">

<TD BGCOLOR="#000000">

<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/tleftblue1agif.gif" BORDER=0></TD>
<TD BGCOLOR="#024070" WIDTH="754">
<CENTER><B>Introduction</B></CENTER></TD>
<TD WIDTH=3><IMG SRC="./images/trightblue1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

</TD>

</TR>

<TR BGCOLOR=#24252f>

<TD>

<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=0 WIDTH="100%">

<TR CLASS=small><TD BGCOLOR="#1C1F22">


<font face="Tahoma, Verdana, Arial" size="-1">

<h3>We Are Back</h3>
<div align="justify">
We are back After haveing problems with our host again<BR>
We are still in the proccess off seting up the board and test system and archive
so PLesae don't report any broken links and things that are not working for a few days while we get things sorted<BR>

<h3>Nemohackers is unique?</h3>

Nemohackers is somewhat unique now,

as we have developed a 'school' system. You read some texts on a certain subject,

then you take an online test through some scripts that we have made and if you get 100%

then you gain 'points'.

<br><br>Every time you gain points a certain script goes and

checks to see how many points you have and then assigns you a rank in this

forum based on how many points you have. There are 11 ranks that require

between 1-100 points to get. <br><br>The more points the higher the rank on the

boards. There will be elevated access granted based on rank and sometimes mod

positions in certain forums.  We are constantly in need of  'test writers', so if your interested please contact us <a href=mailto:f0d@nemohackers.com>here.</a> <br><br>


</div>
<br>
<div align="justify">
<font face="Tahoma, Verdana, Arial" size="-1">
Nemohackers's Graphics Designer Hostile, 
has made some impressive graphics for the site and now we are glad 
to release our very own desktop wallpaper.<br><br>
<center>
<table width=80% cellpadding=2 border=0><tr><td width=50%>

<center>
<a href="./images/nemo800600.jpg"><img src="./images/prevwall.gif" border="0" Alt="800*600"></a>
<font face="Tahoma, Verdana, Arial" size="-1"><br> 800 * 600</td>

<td width=50%>

<center>
<a href="./images/nemo1024768.jpg"><img src="./images/prevwall.gif" border="0" Alt="800*600"></a>
<font face="Tahoma, Verdana, Arial" size="-1"><br> 1024 * 768
</td></tr></table>


</font>


</TD></TR></TABLE>
    <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/bleftdgrey1agif.gif" BORDER=0></TD>
<TD WIDTH="754" BGCOLOR="1C1F22" >  </TD>
<TD WIDTH=3><IMG SRC="./images/brightdgrey1agif.gif" BORDER=0></TD>
</TR>
</TABLE>


</TD></TR></TABLE>






<FONT CLASS="small" FACE="Arial"><BR>

</FONT>
</TD></TR></TABLE>



<FONT CLASS="small" FACE="Arial"><BR>

</FONT> <!----------------3333333333333333333333333------------------> 



<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="0" CELLSPACING="1" WIDTH="100%">

<TR BGCOLOR="#000000">

<TD BGCOLOR="#1c1f22">

<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/tleftblue1agif.gif" BORDER=0></TD>
<TD BGCOLOR="#024070" WIDTH="754">
<CENTER><B>News</B></CENTER></TD>
<TD WIDTH=3><IMG SRC="./images/trightblue1agif.gif" BORDER=0></TD>
</TR>
</TABLE>
<font face="Tahoma, Verdana, Arial" size="-1">
<?php require('news/news.txt');?>
</font>

<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*"><TR>
<TD WIDTH=3><IMG SRC="./images/bleftdgrey1agif.gif" BORDER=0></TD>
<TD WIDTH="754" BGCOLOR="1C1F22"> </TD>
<TD WIDTH=3><IMG SRC="./images/brightdgrey1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

</TD></TR></TABLE>







</td>

<TD BGCOLOR="#000000" VALIGN="top" WIDTH="160">

<!----------------eend top------------>

<!------------left column--------------->

<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="160">

<TR BGCOLOR="#000000">

<TD BGCOLOR="#000000" WIDTH="160">

<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="160">
<TR>
<TD WIDTH=3><IMG SRC="./images/tleftblue1agif.gif" BORDER=0></TD>
<TD BGCOLOR="#024070" WIDTH="154">
<CENTER><CENTER><b>Other</b></CENTER></CENTER></TD>
<TD WIDTH=3><IMG SRC="./images/trightblue1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

</TD>

</TR>



<TR BGCOLOR="#1c1f22">

<TD WIDTH="160" BGCOLOR="#1c1f22" CELLPADDING="2">

<TABLE BORDER="0" CELLPADDING="4" CELLSPACING="0" WIDTH="100%">

<TR CLASS="small">

<TD BGCOLOR="#1C1F22" HEIGHT="426" VALIGN="top">

<!------menu here----------->

<CENTER>

    <?php require('menu2.php'); ?>

</center>

</TD></TR></TABLE>

<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/bleftdgrey1agif.gif" BORDER=0></TD>
<TD WIDTH="754" BGCOLOR="1C1F22"></TD>
<TD WIDTH=3><IMG SRC="./images/brightdgrey1agif.gif" BORDER=0></TD>
</TR>


</TABLE>



</TD></TR></TABLE>







</TD></TR></TABLE>



</TD></TR></TABLE>







<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="750" HEIGHT="2">

<TR BGCOLOR="#024070" HEIGHT="2"><TD BGCOLOR="#024070" HEIGHT="2"></TD></TR></TABLE>
<CENTER><BR><BR>


<center>

<?php

$DIRNAME = "./banners/";	#The path RELATIVE to this script to the dir containing the images.
			#The value should end with a "/" character!
			#This directory should contain ONLY images.

$images = array(); 	#Holds the list of images to choose randomly from.
$file_handle=opendir($DIRNAME); 
$x = 0;
while ($file = readdir($file_handle)) { 
	if($file == '.' || $file == '..') { continue; }
	if(is_dir($DIRNAME.$file)) { continue; }
        $images[$x] = $DIRNAME . $file; 
	$x += 1;
}
closedir($file_handle); 

function DisplayRandomImage() {
	global $images;
	if (count($images) > 0) {
		srand((double)microtime()*1000000);
		$rnd_img = rand(0,(count($images) - 1));
		return $rnd_img;
	}
}
?>

<IMG SRC="<?=$images[DisplayRandomImage()];?>" ALT="">



<br>
<a href="uploader2.php3"><b>Get your banner here!<b></a>
</TR>
</TABLE>


    <?php require('footer.php'); ?>



</BODY>

</HTML>



