<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 TRANSITIONAL//EN">
<HTML>
<HEAD>
<TITLE>[ nemo hackers ]</TITLE>
<?php require('meta.php'); ?>
<?php require('header.php'); ?>


<!--start the individual page-->







<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="5" CELLSPACING="0" WIDTH="750"><TR>

<TD BGCOLOR="#000000" VALIGN="top" WIDTH="160">
<!-- corners -->

<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="160">

<TR BGCOLOR=""><TD>
<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="160">
<TR>
<TD WIDTH=3><IMG SRC="./images/tleftblue1agif.gif" BORDER=0></TD>
<TD BGCOLOR="#024070" WIDTH="154">
<CENTER><CENTER><b>Menu</b></CENTER></CENTER></TD>
<TD WIDTH=3><IMG SRC="./images/trightblue1agif.gif" BORDER=0></TD>
</TR>
</TABLE>
</TR>



<TR BGCOLOR="#1c1f22">

<TD WIDTH="160" BGCOLOR="#1c1f22" CELLPADDING="2">

<TABLE BORDER="0" CELLPADDING="4" CELLSPACING="0" WIDTH="100%">

<TR CLASS="small">

<TD BGCOLOR="#1C1F22" HEIGHT="426" VALIGN="top">

<CENTER>

    <?php require('menu.php'); ?>

</CENTER>











</TD></TR></TABLE>
<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/bleftdgrey1agif.gif" BORDER=0></TD>
<TD WIDTH="754" BGCOLOR="1C1F22">
<TD WIDTH=3><IMG SRC="./images/brightdgrey1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

</TD></TR></TABLE></TD>

<!------------eend left column--------------->

<!------------rright column--------------->

<TD BGCOLOR="#000000" VALIGN="top">

<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="100%">

<TR VALIGN="top"><TD BGCOLOR="#000000">


<!------------------11111111111111111111111111------------------>

<!------------------11111111111111111111111111------------------>

<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="0" CELLSPACING="1" WIDTH="100%">

<TR BGCOLOR="#000000">

<TD BGCOLOR="#000000">

<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/tleftblue1agif.gif" BORDER=0></TD>
<TD BGCOLOR="#024070" WIDTH="754">
<CENTER><B>About Nemohackers</B></CENTER></TD>
<TD WIDTH=3><IMG SRC="./images/trightblue1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

</TD>

</TR>

<TR BGCOLOR=#24252f>

<TD>

<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=0 WIDTH="100%">

<TR CLASS=small><TD BGCOLOR="#1C1F22">

<br>
<font face="verdana" size="2">


<center>
<form name="jform">
<TABLE width="100%">
<tr>
<td bgcolor=#024070>
<font size=-1 color=white><b>
Jpilot jIRC applet only support Netscape4.0, IE4.0 or above.<br>
Please grant the permission when the pop up window appears from Netscape
and IE.</b><br>
</font>
</td>
</tr>

<TR><TD align=center>

<nobr>
 <applet archive="jirc/jirc_nss.zip" code=Chat.class width=520 height=320 >
      <param name="CABBASE" value="jirc/jirc_mss.cab">
      ...
      <param name="LicenseKey" value="3650390587-04349123-668888865509090434912314604631581423601309-01349213340493449293777894566083136688779311198178679346936688888655090931281760831366881485064414043488">
      ...

<param name="ServerPort" value="6667">
<param name="ServerName1" value="irc.r-fx.org">
<param name="ServerName2" value="irc.ins.net.uk">
<param name="ServerName3" value="irc.prison.net">

<param name="Channel1" value="Nemohackers">
<param name="Channel2" value="chat">
<param name="Channel3" value="home">
<param name="Channel4" value="deadworld">


<param name="AllowURL" value="true">
<param name="AllowIdentd" value="true">

<param name="IgnoeMOTD" value="true">

<param name="WelcomeMessage" value="Nemo is everything">
<param name="RealName" value="Nemohackers.com User">
<param name="NickName" value="Nemo">
<param name="UserName" value="Nemo">
<param name="isLimitedServers" value="true">
<param name="isLimitedChannels" value="true">


<param name="BackgroundColor" value="2,64,112">
<param name="TextColor" value="black">
<param name="TextScreenColor" value="white">
<param name="ListTextColor" value="blue">
<param name="TitleBackgroundColor" value="black">
<param name="TitleForegroundColor" value="white">
<param name="NickNameColor" value="3">

<param name="IgnoreServerMsg" value="true">

<param name="TextFontName" value="Arial">
<param name="TextFontSize" value="12">

<param name="LogoBgColor" value="white">
<param name="BorderVsp" value="2">
<param name="DirectStart" value="false">

<param name="AliasList" value="/m=/msg,/t=/topic">
<param name="FilterKeys" value=":) :( :D :P jcool">
<param name="FilterVals" value="smile.gif frown.gif biggrin.gif tongue.gif
IRClogo.gif">

<param name="FieldNamePrivateChatTitle" value="Private Chat with: ">
<param name="FieldNameConnected" value="Connected to server, trying to
login" >

</applet>
<br>

</TD><td width=15><!----margin-----></td></TR>
</TABLE>
</form>

</center>











































  

</TD>

</TR>
</TABLE>





    <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/bleftdgrey1agif.gif" BORDER=0></TD>
<TD WIDTH="754" BGCOLOR="1C1F22">
<TD WIDTH=3><IMG SRC="./images/brightdgrey1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

</TD></TR></TABLE></TD></TR></TABLE></TD></TR></TABLE></TD></TR></TABLE>

</TD></TR></TABLE></TD></TR></TABLE>

<TABLE BGCOLOR=#000000 BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=750 HEIGHT=2>

<TR BGCOLOR="#024070" HEIGHT=2><TD BGCOLOR="#024070" HEIGHT=2></TD></TR></TABLE>

    <?php require('footer.php'); ?>

<BR>

