<!-- www.nemohackers.com -->





<table border="0">

<tr><td width="10" bgcolor="1C1F22"></td><td>

<font face="Tahoma, Verdana, Arial" size="-1">

<b>


<img src="images/folder_small.jpg">&nbsp;

Main</b></center>

</font>

</tr></td>

<tr><td width="10" bgcolor="1C1F22"></td><td>



<font face="Tahoma, Verdana, Arial" size="-1"></FONT>





<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="index.php">

<font face="Tahoma, Verdana, Arial" size="-1">Home</FONT></A>
<font face="Tahoma, Verdana, Arial" size="-1"> <BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="archives.php">Text Archives</A> <BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="uploader.php3">Upload</A> <BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="write.php">Write a txt file</A> <BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="search.php">Search!</A><BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="http://forum.nemohackers.com">Forum</A> <BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="irc.php">IRC chat</A><BR>


<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="dnet.php">DNET Subteam</A><BR>

<br>
<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="projects.php">Projects</A> <BR>


<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="faq.php">FAQ</A> <BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="feedback.php">Feedback</A> <BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="copyright.php">Copyright</A><BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="disclaimer.php">Disclaimer</A><BR>
<br>


<FONT COLOR="#515468">&raquo;</FONT><A HREF="#">Take a Test - DOWN</A><BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="#">Make a Test - DOWN</A><BR>
<br>


<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="about.php">About</A> <BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="staff.php">Staff</A> <BR>

<FONT COLOR="#515468" size=1>&raquo;</FONT> <A HREF="hyperlinks.php">Hyperlinks</A> <BR>
<BR>
</FONT>



</td></tr><tr><td width="10" bgcolor="1C1F22"></td><td>

<br>

<b>

<img src="images/folder_small.jpg">&nbsp;<font face="Tahoma, Verdana, Arial" size="-1">

Online Tools</b></center></font>

</font>

</tr></td>

<tr><td width="10" bgcolor="1C1F22"></td><td>

<font face="Tahoma, Verdana, Arial" size="-1">

<font face="Tahoma, Verdana, Arial" size="-1"></FONT>





<FONT COLOR="#515468" size=1>&raquo;</FONT> 

<A HREF="http://supersane.com/tools/networktools.php">Network Tools</A><BR>






</td></tr><tr><td width="10" bgcolor="1C1F22"></td><td>



</td></tr><tr><td width="10" bgcolor="1C1F22"></td><td>

<font face="Tahoma, Verdana, Arial" size="-1">







</td></tr><tr><td width="10" bgcolor="1C1F22"></td><td>



<font face="Tahoma, Verdana, Arial" size="-1">

<b>

<img src="images/folder_small.jpg">&nbsp;

Search</b></center>

</font>

</tr></td>

<tr><td width="10" bgcolor="1C1F22"></td><td>

<font face="Tahoma, Verdana, Arial" size="-1">

<font face="Tahoma, Verdana, Arial" size="-1"></FONT>

          <FONT FACE="verdana" SIZE="1">



<form method=post action=search.php>
What for?<br>
<input size="12" type=text  style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1">

  <br><br>Results Per Page<br>

<SELECT name="rpp" style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1">

<option value="10">10</option>

<option value="15">15</option>

<option value="20">20</option>

<option value="25">25</option>

<option value="50">50</option>

<option value="100">100</option>

<option value="10000000000">All</option>

</SELECT>

<br><br>

Search Depth:<br>

<SELECT name="sdep" style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1">

<option value="100">100</option>

<option value="150">150</option>

<option value="200">200</option>

<option value="250">250</option>

<option value="500" selected>500</option>

<option value="1000">1000</option>

<option value="2000">2000</option>

<option value="5000">5000</option>

<option value="all">Max</option>

</SELECT>

<br>
<br>
<input type=submit value="Search!" style="background-color: #003366; background-attachment: scroll; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 10px; color: #FFFFFF; border-height: 2; text-decoration: none; font-weight: bold; border: 1 solid #000000; padding: 1">

<font face="Tahoma, Verdana, Arial" size="-1">
</form>
<B>


</tr></td>


</FONT>





</table>













</CENTER>



