<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 TRANSITIONAL//EN">

<HTML>

<HEAD>

<TITLE>[ nemo hackers ]</TITLE>

<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1" CHARSET="iso-8859-1">

<META NAME="keywords" CONTENT=

"newbie, newbies, newbiesplace, newbiezplace, learn to hack, how to hack, how do i hack,hack hotmail, hacking hotmail, hack yahoo, hacking yahoo, hacking tools, hacking programs, hacking site, newby, newbeisplace, newbeizplace,">

<META NAME="description" CONTENT="NewbiezPlace.com - Where newbies come to learn the art of hacking. This site is a vast resource for hacking methodology and toolz">

<META NAME="robots" CONTENT="FOLLOW,INDEX">





    <?php require('header.php'); ?>







<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="5" CELLSPACING="0" WIDTH="750"><TR>

<TD BGCOLOR="#000000" VALIGN="top" WIDTH="160">
<!-- corners -->

<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="160">

<TR BGCOLOR=""><TD>
<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="160">
<TR>
<TD WIDTH=3><IMG SRC="./images/tleftblue1agif.gif" BORDER=0></TD>
<TD BGCOLOR="#024070" WIDTH="154">
<CENTER><CENTER><b>Menu</b></CENTER></CENTER></TD>
<TD WIDTH=3><IMG SRC="./images/trightblue1agif.gif" BORDER=0></TD>
</TR>
</TABLE>
</TR>



<TR BGCOLOR="#1c1f22">

<TD WIDTH="160" BGCOLOR="#1c1f22" CELLPADDING="2">

<TABLE BORDER="0" CELLPADDING="4" CELLSPACING="0" WIDTH="100%">

<TR CLASS="small">

<TD BGCOLOR="#1C1F22" HEIGHT="426" VALIGN="top">

<CENTER>

    <?php require('menu.php'); ?>

</CENTER>











</TD></TR></TABLE>
<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/bleftdgrey1agif.gif" BORDER=0></TD>
<TD WIDTH="754" BGCOLOR="1C1F22">
<TD WIDTH=3><IMG SRC="./images/brightdgrey1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

</TD></TR></TABLE></TD>

<!------------eend left column--------------->

<!------------rright column--------------->

<TD BGCOLOR="#000000" VALIGN="top">

<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="100%">

<TR VALIGN="top"><TD BGCOLOR="#000000">


<!------------------11111111111111111111111111------------------>

<!------------------11111111111111111111111111------------------>

<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="0" CELLSPACING="1" WIDTH="100%">

<TR BGCOLOR="#000000">

<TD BGCOLOR="#000000">

<TABLE BGCOLOR="#024070" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/tleftblue1agif.gif" BORDER=0></TD>
<TD BGCOLOR="#024070" WIDTH="754">
<CENTER><B>Staff</B></CENTER></TD>
<TD WIDTH=3><IMG SRC="./images/trightblue1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

</TD>

</TR>

<TR BGCOLOR=#24252f>

<TD>

<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=0 WIDTH="100%">

<TR CLASS=small><TD BGCOLOR="#1C1F22">


<!-- MAIN CONTENT -->

<BR>
<CENTER>
<TABLE WIDTH="90%" BORDER="0">
<TR>
    <TD BGCOLOR="#024070"><b>Handle</b></TD>
    <TD BGCOLOR="#024070"><b>Job</b></TD>
    <TD BGCOLOR="#024070"><b>Email</b></TD>
    <TD BGCOLOR="#024070"><b>UIN</b></TD>
</TR>
<TR>
    <TD BGCOLOR="#FFFFFF"><FONT COLOR="#000000"><B>f0d</B></FONT></TD>
    <TD BGCOLOR="#FFFFFF"><FONT COLOR="#000000">CEO, PHP programmer, webmaster, Administrator</FONT></TD>
    <TD BGCOLOR="#FFFFFF"><CENTER><A HREF="f0d@nemohackers.com"><IMG SRC="images/email.gif" BORDER=0></A></CENTER></TD>
    <TD BGCOLOR="#FFFFFF"><CENTER><A HREF="www.icq.com"><IMG SRC="images/icq.gif" ALT="118600289" BORDER=0></CENTER></A></TD>
</TR>
<TR>
    <TD BGCOLOR="#FFFFFF"><FONT COLOR="#000000"><B>NEILLER</B></FONT></TD>
    <TD BGCOLOR="#FFFFFF"><FONT COLOR="#000000">CEO, webmaster, Administrator</FONT></TD>
    <TD BGCOLOR="#FFFFFF"><CENTER><A HREF="neiller@nemohackers.com"><IMG SRC="images/email.gif" BORDER=0></A></CENTER></TD>
    <TD BGCOLOR="#FFFFFF"><CENTER><A HREF="www.icq.com"><IMG SRC="images/icq.gif" ALT="97170643" BORDER=0></CENTER></A></TD>
</TR>
<TR>
    <TD BGCOLOR="#FFFFFF"><FONT COLOR="#000000"><B>Xavic</B></FONT></TD>
    <TD BGCOLOR="#FFFFFF"><FONT COLOR="#000000">CEO, PHP programmer, Administrator</FONT></TD>
    <TD BGCOLOR="#FFFFFF"><CENTER><A HREF="xavic_doute@hotmail.com"><IMG SRC="images/email.gif" BORDER=0></A></CENTER></TD>
    <TD BGCOLOR="#FFFFFF"><CENTER><A HREF="www.icq.com"><IMG SRC="images/icq.gif" ALT="52929704" BORDER=0></CENTER></A></TD>
</TR>
<TR>
    <TD BGCOLOR="#FFFFFF"><FONT COLOR="#000000"><B>Tvwize</B></FONT></TD>
    <TD BGCOLOR="#FFFFFF"><FONT COLOR="#000000">Webmaster, Administrator</FONT></TD>
    <TD BGCOLOR="#FFFFFF"><CENTER><A HREF="tvwize@nemohackers.com"><IMG SRC="images/email.gif" BORDER=0></A></CENTER></TD>
    <TD BGCOLOR="#FFFFFF"><CENTER><A HREF="www.icq.com"><IMG SRC="images/icq.gif" ALT="113277668" BORDER=0></CENTER></A></TD>
</TR>
</TABLE>
</CENTER>

<BR><BR>
We would like to thank to following <A HREF="http://forum.nemohackers.com">Forum</A> Moderators:
<BLOCKQUOTE>
<b>Warphace, Teck7, ev|L1, and more that I have forgotton.</b>
</BLOCKQUOTE>





</TD>

</TR>
</TABLE>













































    <TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="*">
<TR>
<TD WIDTH=3><IMG SRC="./images/bleftdgrey1agif.gif" BORDER=0></TD>
<TD WIDTH="754" BGCOLOR="1C1F22">
<TD WIDTH=3><IMG SRC="./images/brightdgrey1agif.gif" BORDER=0></TD>
</TR>
</TABLE>

</TD>

</TR>
</TABLE>






</TD></TR></TABLE></TD></TR></TABLE></TD></TR></TABLE></TD></TR></TABLE>

</TD></TR></TABLE></TD></TR></TABLE>

<TABLE BGCOLOR=#000000 BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=750 HEIGHT=2>

<TR BGCOLOR="#024070" HEIGHT=2><TD BGCOLOR="#024070" HEIGHT=2></TD></TR></TABLE>

    <?php require('footer.php'); ?>

<BR>

