<?php
//bf22496d5cf04ddbdbf8c6438e2e96fd


$db = mysql_connect("64.156.139.240","supersane","1419");
mysql_select_db("supersane",$db);

$sql = "INSERT INTO test12345 VALUES ( '1', 'How many apples are in here?', '1', '5', '3', '8', 'a2')";
$result = mysql_query($sql,$db);

$sql = "INSERT INTO test12345 VALUES ( '2', 'What time is it?', '8:00', '7:00', 'half past 7', 'pigs', 'a3')";
$result = mysql_query($sql,$db);
$sql = "INSERT INTO test12345 VALUES ( '3', 'Where?', 'over there stupid.', 'are you a moron or what?', 'I believe its back that way a little bit.', 'right here.', 'a4')";
$result = mysql_query($sql,$db);
$sql = "INSERT INTO test12345 VALUES ( '4', 'What does \'IP\' in IP Address stand for?', 'Ice Puke', 'Internet Pokemon', 'Internet Protocol', 'Intern Pleasantries', 'a3')";
$result = mysql_query($sql,$db);
$sql = "INSERT INTO test12345 VALUES ( '5', 'How many bits does it take to store an IP address?', '2', '8', '16', '32', 'a4')";
$result = mysql_query($sql,$db);
$sql = "INSERT INTO test12345 VALUES ( '6', 'How many bits does it take to store an IP address?1111', '2', '8', '16', '32', 'a4')";
$result = mysql_query($sql,$db);
$sql = "INSERT INTO test12345 VALUES ( '7', 'How many bits does it take to store an IP address?222222', '2', '8', '16', '32', 'a4')";
$result = mysql_query($sql,$db);
$sql = "INSERT INTO test12345 VALUES ( '8', 'How many bits does it take to store an IP address?333333', '2', '8', '16', '32', 'a4')";
$result = mysql_query($sql,$db);
$sql = "INSERT INTO test12345 VALUES ( '9', 'How many bits does it take to store an IP address?444444', '2', '8', '16', '32', 'a4')";
$result = mysql_query($sql,$db);
$sql = "INSERT INTO test12345 VALUES ( '10', 'How many bits does it take to store an IP address?55555', '2', '8', '16', '32', 'a4')";
$result = mysql_query($sql,$db);
$sql = "INSERT INTO test12345 VALUES ( '11', 'sadgsadfg dsfg ds d gdfg fds gdf?dsf', 'dsfg dsf g', 'dsf gsdf', 'g sdfg s', 'fdsg df', 'a1')";
$result = mysql_query($sql,$db);
$sql = "INSERT INTO test12345 VALUES ( '12', 'this is question 12', 'sadg', 'gd', 'ds fgdsf', 'sfgsdf', 'a3')";
$result = mysql_query($sql,$db);


?>


