<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">



<?php



require("includes/header.php");



?>



<TABLE border="0" width="100%">



      <TR valign="top">



        <TD width="20%">



          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="2" width="100%">



            <TR valign="top">



              <TD background="images/back.JPG" width="100%">



                <CENTER>



               <FONT face="Verdana, Helvetica" color="white" size="2"><B>Archives</B></FONT>



                </CENTER>



              </TD>



            </TR>



            <TR valign="top">



              <TD width="100%">



           	<CENTER>

                  <FONT face="Verdana, Helvetica" color="white" size="1">

                  to your right MENU





                 </FONT>



		</CENTER>

              </TD>



            </TR>


          </TABLE>



          <BR>



           



 

        </TD>



        <TD width="80%">



          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="4" width="100%">



            <TR valign="top">



              <TD background="images/back.JPG" width="100%">



                <CENTER>



                  <FONT face="Verdana, Helvetica" color="white" size="2"><B>Search</B></FONT>



                </CENTER>



              </TD>



            </TR>



            <TR valign="top">



              <TD width="100%">



                <CENTER>



                  <FONT face="Verdana, Helvetica" size="2"><B>Search Nemohackers: &nbsp;&nbsp; 
				  <INPUT type="text" name="search" size="20" maxlength="50">&nbsp; <INPUT type="submit" value="Search">



                  <BR>



                  </B></FONT>



                </CENTER>



              </TD>



            </TR>



          </TABLE>



          <BR>



           <!-- News and development --> 



          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="4" width="100%">



            <TR valign="top">



              

          <TD background="back.JPG" width="100%">
		  <FONT face="Verdana, Helvetica" color="white" size="2">
		  Were pretty unsorted at the Moment. get around to it soon :)
		  
<br>
<br>
		  
		  
		  <?php include('dir.php');?></TD>

            </TR>

          </TABLE>

        </TD>

      </TR>

    </TABLE>







<?php require("includes/footer.php");?><BR>











