<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">



<?php



require("includes/header.php");



?>



<TABLE border="0" width="100%">
  <TR valign="top"> 
    <TD width="86%"> 
      <!-- News and development -->
      <div align="center"> 
        <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="4" width="94%">
          <TR valign="top"> 
            <TD  background="images/back.JPG" width="100%"> 
              <CENTER>
                <FONT face="Verdana, Helvetica" color="white" size="2"><b>Nemohackers 
                forums</b></FONT> 
              </CENTER>
            </TD>
          </TR>
          <TR valign="top"> 
            <TD width="100%"> 
              <table width=100% border=0>
                <tr> 
                  <td width=* valign=top> 
                    <div align="center">
                      <p><br>
                        <font size="2" face="Verdana, Arial, Helvetica, sans-serif"><a href="http://ww.r-fx.org/%7Enemo/phpBB">Mirror 
                        1</a> | <a href="http://supersane.com/phpBB">Mirror 2</a></font></p>
                      <p><font face="Verdana, Arial, Helvetica, sans-serif" size="2">Note: 
                        Mirror 1 is a little faster at times</font></p>
                      <p>&nbsp;</p>
                    </div>
                  </td>
                </tr>
              </table>
              <BR></FONT>
              </TD>
          </TR>
        </TABLE>
      </div>
</TABLE>



<?php require("includes/footer.php");?><BR>








