<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

<?php

require("includes/header.php");

?>

<TABLE border="0" width="100%">

      <TR valign="top">

        <TD width="20%">

          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="2" width="100%">

            <TR valign="top">

              <TD background="images/back.JPG" width="100%">

                <CENTER>

               <FONT face="Verdana, Helvetica" color="white" size="2"><B>Modules</B></FONT>

                </CENTER>

              </TD>

            </TR>

            <TR valign="top">

              <TD width="100%">

           	<CENTER>
                  <FONT face="Verdana, Helvetica" color="white" size="1">
                  <?php

                    require("includes/modules.txt");

                    ?></FONT>

		</CENTER>
              </TD>

            </TR>

          </TABLE>

          <BR>

           

          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="2" width="100%">

            <TR valign="top">

              <TD background="images/back.JPG" width="100%">

                <CENTER>

              <FONT face="Verdana, Helvetica" color="white" size="2"><B>???????</B></FONT>

                </CENTER>

              </TD>

            </TR>

            <TR valign="top">

              <TD width="100%">
????????????

<br>????????????

???????


              </TD>

            </TR>

          </TABLE>

          <BR>

           

          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="2" width="100%">

            <TR valign="top">

              <TD background="images/back.JPG" width="100%">

                <CENTER>

            <FONT face="Verdana, Helvetica" color="white" size="2"><B>???????????????</B></FONT>

                </CENTER>

              </TD>

            </TR>

            <TR>

              <TD width="100%">
???????????????
<br>??????????
<br>???????????
<br>???????

              </TD>

            </TR>

          </TABLE>

        </TD>

        <TD width="80%">

          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="4" width="100%">

            <TR valign="top">

              <TD background="images/back.JPG" width="100%">

                <CENTER>

                  <FONT face="Verdana, Helvetica" color="white" size="2"><B>Search</B></FONT>

                </CENTER>

              </TD>

            </TR>

            <TR valign="top">

              <TD width="100%">

                <CENTER>

                  <FONT face="Verdana, Helvetica" size="2"><B>Search Nemohackers: &nbsp;&nbsp; <INPUT type="text" name="search" size="20" maxlength="50">&nbsp; <INPUT type="submit" value="Search">

                  <BR>

                  </B></FONT>

                </CENTER>

              </TD>

            </TR>

          </TABLE>

          <BR>

           <!-- News and development --> 

          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="4" width="*">

            <TR valign="top">

              <TD background="images/back.JPG" width="100%">

                <CENTER>

                  <FONT face="Verdana, Helvetica" color="white" size="2"><B>About</B></FONT>

                </CENTER>

              </TD>

            </TR>

            <TR valign="top">

              <TD width="100%">

                <FONT face="Verdana, Helvetica" size="2"><center>
				Well as we have said before the concept of nemohackers has changed drematically, and here is one example of our concept, in most site you have a download page where you reading boring texts and downloads apps, now where the hell is your inspiration?  Well instead of those boring pages were compiling tests / modules for you to learn which have more interactivity..
				<BR>

                <BR>

                </FONT>

              </TD>

            </TR>

          </TABLE>

		     </TD>

            </TR>

          </TABLE>


<?php require("includes/footer.php");?><BR>





