<html>

<head>

<title>music</title>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

</head>



<body bgcolor="black">

<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=4,0,2,0" width="18" height="18">

  <param name=movie value="http://www.r-fx.org/~nemo/music.swf">

  <param name=quality value=high>

  <embed src="http://www.r-fx.org/~nemo/music.swf" quality=high pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" type="application/x-shockwave-flash" width="18" height="18">

  </embed> 

</object> 

</body>

</html>