<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 3.2//EN">

<?php require("includes/header.php");?>

    <TABLE border="0" width="100%">
      <TR valign="top">
        <TD width="14%">
          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="2" width="83%">
            <TR valign="top">
              <TD background="images/back.JPG" width="100%">
                <CENTER>
                  <FONT face="Verdana, Helvetica" color="white" size="2"><B>Home</B></FONT>
                </CENTER>
              </TD>
            </TR>
            <TR valign="top">
              <TD width="70%">
                <CENTER>
                  <FONT face="Verdana, Helvetica" color="white" size="1">
				  
				  <?php require("includes/home.txt");?></FONT>
                </CENTER>
              </TD>
            </TR>
          </TABLE>
          <BR>
           
          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="2" width="83%">
            <TR valign="top">
              <TD background="images/back.JPG" width="70%">
                <CENTER>
                  <FONT face="Verdana, Helvetica" color="white" size="2"><B>User Login</B></FONT>
                </CENTER>
              </TD>
            </TR>
            <TR valign="top">
              <TD width="70%">
                <?php require('login.php'); ?>
              </TD>
            </TR>
          </TABLE>
          <BR>
           
          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="2" width="82%">
            <TR valign="top">
              <TD background="images/back.JPG" width="70%">
                <CENTER>
                  <FONT face="Verdana, Helvetica" color="white" size="2"><B>Search</B></FONT>
                </CENTER>
              </TD>
            </TR>
            <TR>
              <TD width="70%">
                <CENTER>
                  <FONT face="Verdana, Helvetica" color="white" size="1">
				  <?php require('includes/search.txt'); ?></FONT>
                </CENTER>
              </TD>
            </TR>
          </TABLE>
        </TD>
        <TD width="86%">
          <!-- News and development -->
          <TABLE border="1" bordercolor="#003366" cellspacing="0" cellpadding="4" width="100%">
            <TR valign="top">
              <TD background="images/back.JPG" width="100%">
                <CENTER>
                  <FONT face="Verdana, Helvetica" color="white" size="2"><B>Nemohackers Staff</B></FONT>
                </CENTER>
              </TD>
            </TR>
            <TR valign="top">
              <TD width="100%">
                <TABLE width="100%" border="0">
                  <TR>
                    <TD width="*" valign="top">
                      
					  
<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=0 WIDTH="100%"><TR>



<TD VALIGN="top"><H3>Site Administrators</H3><img src="images/profile.gif" BORDER="0"></TD></TR>
<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">F.o.D &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:fod@Nemohackers.com"><img src="images/email.gif" BORDER="0">&nbsp;fod@Nemohackers.com</A>
</TD><TD WIDTH="25%" HEIGHT="18"><B CLASS="my"><img src="images/icq.gif" BORDER="0">&nbsp;118600289</TD></TR>


<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">NEILLER &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:NEILLER@Nemohackers.com"><img src="images/email.gif" BORDER="0">&nbsp;neiller@Nemohackers.com</A>
</TD><TD WIDTH="25%" HEIGHT="18"><B CLASS="my"><img src="images/icq.gif" BORDER="0">&nbsp;97170643
</TD></TR>

<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">Butworth &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0">
</TD><TD WIDTH="45%" HEIGHT="18"><B CLASS="my"><A HREF="mailto:butworth@Nemohackers.com"><img src="images/email.gif" BORDER="0">&nbsp;butworth@Nemohackers.com</A></TD><TD WIDTH="25%" HEIGHT="18">
<B CLASS="my"><img src="images/icq.gif" BORDER="0">&nbsp;103603680</TD></TR>

<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">Unregistered &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:unregistured@Nemohackers.com">
<img src="images/email.gif" BORDER="0">&nbsp;unregistured@Nemohackers.com</A>
</TD><TD WIDTH="25%" HEIGHT="18">
<B CLASS="my"><img src="images/icq.gif" BORDER="0">&nbsp;n/a
</TD></TR>

<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">Tvwize &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:Tvwize@Nemohackers.com"><img src="images/email.gif" BORDER="0">&nbsp;Tvwize@Nemohackers.com</A>
</TD><TD WIDTH="25%" HEIGHT="18"><B CLASS="my"><img src="images/icq.gif" BORDER="0">&nbsp;113277668
</TD></TR>

</TABLE>







<BR>

<TABLE BORDER=0 CELLPADDING=4 CELLSPACING=0 WIDTH="100%">		
<TR><TD VALIGN="top"><H3>Board Moderators</H3><img src="images/profile.gif" BORDER="0"></TD></TR>       
<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">Feeble &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:Feeble@q3arena.com"><img src="images/email.gif" BORDER="0">&nbsp;Feeble@q3arena.com</A>
</TD><TD WIDTH="25%" HEIGHT="18">
<B CLASS="my"><img src="images/icq.gif" BORDER="0">92046148</TD></TR>      


<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">B1nary &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:the_wizard_05@usa.net">
<img src="images/email.gif" BORDER="0">&nbsp;the_wizard_05@usa.net</U></A>
</TD><TD WIDTH="25%" HEIGHT="18">
<B CLASS="my"><img src="images/icq.gif" BORDER="0">47420417</TD></TR> 


<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">Alicia &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:tangyquotepie@hotmail.com"><img src="images/email.gif" BORDER="0">&nbsp;tangyquotepie@hotmail.com</U></A>
</TD><TD WIDTH="25%" HEIGHT="18"><B CLASS="my"><img src="images/icq.gif" BORDER="0">96339410
</TD></TR>                   

<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">Tech7 &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:ryan@r-fx.net"><img src="images/email.gif" BORDER="0">&nbsp;ryan@r-fx.net</A>
</TD><TD WIDTH="25%" HEIGHT="18">
<B CLASS="my"><img src="images/icq.gif" BORDER="0">&nbsp;n/a
</TD></TR>                                            



<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">Elyisum &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:"><img src="images/email.gif" BORDER="0">&nbsp;n/a</A>
</TD><TD WIDTH="25%" HEIGHT="18">
<B CLASS="my"><img src="images/icq.gif" BORDER="0">&nbsp;n/a
</TD></TR>                   


<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">GODBOD &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:GODBOD@hotmail.com"><img src="images/email.gif" BORDER="0">&nbsp;GODBOD@hotmail.com</A>
</TD><TD WIDTH="25%" HEIGHT="18">
<B CLASS="my"><img src="images/icq.gif" BORDER="0">&nbsp;n/a
</TD></TR>                


<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">Infinite &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:ashoey@uswest.net">
<img src="images/email.gif" BORDER="0">&nbsp;ashoey@uswest.net</A>
</TD><TD WIDTH="25%" HEIGHT="18">
<B CLASS="my"><img src="images/icq.gif" BORDER="0">&nbsp;n/a
</TD></TR>

<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">treetop &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:">
<img src="images/email.gif" BORDER="0">&nbsp;n/a</A>
</TD><TD WIDTH="25%" HEIGHT="18">
<B CLASS="my"><img src="images/icq.gif" BORDER="0">&nbsp;n/a
</TD></TR>

<TR><TD WIDTH="30%" HEIGHT="18"><B CLASS="my">warphace &nbsp;&nbsp;@<BR>
<img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"><img src="images/star2.gif" BORDER="0"></TD><TD WIDTH="45%" HEIGHT="18">
<B CLASS="my"><A HREF="mailto:">
<img src="images/email.gif" BORDER="0">&nbsp;n/a</A>
</TD><TD WIDTH="25%" HEIGHT="18">
<B CLASS="my"><img src="images/icq.gif" BORDER="0">&nbsp;104671052
</TD></TR>






</TD></TR></TABLE>		

					  
					  
                   
                    </TD>
                  </TR>
                </TABLE>
                <BR>
                 
              </TD>
            </TR>
          </TABLE>
        </TD>
      </TR>
    </TABLE>
    <?php require("includes/footer.php");?><BR>


