A||||1||elite33177||Is Any One here?||||4||||jr||00000003
Z||000000||elite33177||05-07-2001||01:28 AM||elite33177@yahoo.com||Hello out there is any one there?<BR>  <IMG SRC="confused.gif" border="0"> <BR>I would like some sort of feed back and not talk out to empty space...||63.59.167.4||reg||4||jr||00000003||yes
Z||000001||f0d||05-07-2001||03:53 AM||fod@nemohackers.com||Yeah I'm here...<P>We're back online, whooohoooo!||195.92.67.66||reg||1||f0d||00000004||yes
