# CP Entry Page

&TBT; #Table Border Top in cp_common.pl

&HeaderRow(qq%Current Status of $vars_config{BBName}%, "2", "#5d7790", "#FFFFFF", "left", "2");

&HeaderRow(qq%You have $member_count registered members.<BR>
You have $forum_total forums.<BR>
Page views this month ($GotTime{mon}/$GotTime{JSYear}): $monthly_hits<BR>
Your message board is $bb_status.<BR>%, "2", "#FFFFFF", "#000000", "left", "2");

&TBB; #Table Border Bottom in cp_common.pl


