
<table border="1" bordercolor="#003366" cellspacing="0" cellpadding="2"
width="100%"><tr><td background="back.JPG">

<font face="Verdana, Helvetica" color="white" size="2"><b>
<center><b>About Nemohackers</b></font>
</td></tr><tr><td>
<FONT face="Verdana, Helvetica" size="2"><center>
This site is not dedicated to the illegal activities in
which you proclaim to be a thrill. "It is about computer exploration; The
power to adapt and overcome obstacles
 and security measures; For the personal benefit, satisfaction, and the rush
of entry, into
an unknown and constantly changing technological world.<br><b>"WE ARE HACKERS"</b>
- <i>Proxykillah</i>
<br>
<br>

</td>
</tr>
</table>
