<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 TRANSITIONAL//EN">
<HTML>
<HEAD>
<TITLE>[ nemo hackers ]</TITLE>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1" CHARSET="iso-8859-1">
<META NAME="keywords" CONTENT=
"newbie, newbies, newbiesplace, newbiezplace, learn to hack, how to hack, how do i hack,hack hotmail, hacking hotmail, hack yahoo, hacking yahoo, hacking tools, hacking programs, hacking site, newby, newbeisplace, newbeizplace,">
<META NAME="description" CONTENT="NewbiezPlace.com - Where newbies come to learn the art of hacking. This site is a vast resource for hacking methodology and toolz">
<META NAME="robots" CONTENT="FOLLOW,INDEX">


    <?php require('header.php'); ?>



<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="5" CELLSPACING="0" WIDTH="750"><TR>
<TD BGCOLOR="#000000" VALIGN="top" WIDTH="160">
<TABLE BGCOLOR="#1c1f22" BORDER="0" CELLPADDING="2" CELLSPACING="1" WIDTH="160">
<TR BGCOLOR="#515468"><TD BGCOLOR="#024070" WIDTH="160">
<CENTER><CENTER CLASS="small_uppercase">M E N U</CENTER></CENTER>
</TD></TR>
<TR BGCOLOR="#1c1f22">
<TD WIDTH="160" BGCOLOR="#1c1f22" CELLPADDING="2">
<TABLE BORDER="0" CELLPADDING="4" CELLSPACING="0" WIDTH="100%">
<TR CLASS="small">
<TD BGCOLOR="#1C1F22" HEIGHT="426" VALIGN="top">
<CENTER>
    <?php require('menu.php'); ?>
</CENTER>





</TD></TR></TABLE>
</TD></TR></TABLE></TD>
<!------------eend left column--------------->
<!------------rright column--------------->
<TD BGCOLOR="#000000" VALIGN="top">
<TABLE BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="100%">
<TR VALIGN="top"><TD BGCOLOR="#000000">
<!------------------11111111111111111111111111------------------>
<TABLE BGCOLOR="#1c1f22" BORDER="0" CELLPADDING="0" CELLSPACING="1" WIDTH="100%">
<TR BGCOLOR="#515468">
<TD BGCOLOR="#024070">
<CENTER CLASS="small_uppercase"><SPAN CLASS="small"><FONT COLOR="#80899f" FACE="Arial"><B>.</B></FONT>
<B><FONT COLOR="#b1b6c5" FACE="Arial">:</FONT> <FONT FACE="Arial"><FONT COLOR="#ffffff">: I
<FONT COLOR="#b1b6c5">·</FONT> N <FONT COLOR="#b1b6c5">·</FONT> T <FONT COLOR="#b1b6c5">·</FONT> R 
<FONT COLOR="#b1b6c5">·</FONT> 0</FONT> <FONT COLOR="#ffffff">:</FONT>
<FONT COLOR="#b1b6c5">: <FONT COLOR="#80899f">.</FONT></FONT></FONT></B></SPAN></CENTER>
</TD>
</TR>

<TR BGCOLOR="#24252f"><TD>
<TABLE BORDER="0" CELLPADDING="4" CELLSPACING="0" WIDTH="100%">
<TR CLASS="small"><TD BGCOLOR="#1C1F22"><FONT FACE="Verdana">

<font face="Tahoma, Verdana, Arial" size="-1">
<h3>Anncoucement</h3>
<div align="justify">
Nemohackers.com is back. <b>*cheers from users.</b> Nemohackers is somewhat unique now,
as we have developed a 'school' system. You read some texts on a certain subject, 
then you take an online test through some scripts that we have made and if you get 100%
then you gain 'points'. 
<br><br>Every time you gain points a certain script goes and
checks to see how many points you have and then assigns you a rank in this
forum based on how many points you have. There are 11 ranks that require
between 1-100 points to get. <br><br>The more points the higher the rank on the
boards. There will be elevated access granted based on rank and sometimes mod
positions in certain forums.  We are constantly in need of  'test writers', so if your interested please contact us <a href=mailto:f0d@nemohackers.com>here.</a> <br><br>
</div>
</font>
</TD></TR></TABLE>
</TD></TR></TABLE>

<FONT CLASS="small" FACE="Arial"><BR>
</FONT> <!----------------2222222222222222222222222------------------> 

<TABLE BGCOLOR="#1c1f22" BORDER="0" CELLPADDING="0" CELLSPACING="1" WIDTH="100%">
<TR BGCOLOR="#515468"><TD BGCOLOR="#024070">
<CENTER CLASS="small_uppercase"><SPAN CLASS="small">
<FONT COLOR="#80899f" FACE="Arial, Helvetica, sans-serif"><B>.</B></FONT> <B>
<FONT COLOR="#b1b6c5" FACE="Arial">:</FONT> 
<FONT FACE="Arial"><FONT
COLOR="#ffffff">: W <FONT COLOR="#b1b6c5">·</FONT> H <FONT COLOR="#b1b6c5">·
</FONT> Y <FONT COLOR="#b1b6c5">·</FONT> ? :</FONT> 
<FONT COLOR="#b1b6c5">: <FONT COLOR="#80899f">
.</FONT></FONT></FONT></B></SPAN></CENTER>
</TD></TR>

<TR BGCOLOR="#24252f">
<TD></TD></TR>

<TR CLASS="small">
<TD BGCOLOR="#1C1F22">

<font face="Tahoma, Verdana, Arial" size="-1">
<BR>This site aims to assist the Newbie reach there ultimate goal. 
Please feal free to send us feedback with your comments and questions, good or bad. Contacts
can be found in the contacts page.</FONT>
<P ALIGN="center"><I><FONT FACE="Verdana">This site is not dedicated to the illegal activities in<BR>
which you proclaim to be a thrill. "It is about computer exploration; The power to adapt and overcome obstacles
 and security measures; For the personal benefit, satisfaction, and the rush of entry, into
an unknown and constantly changing technological world."WE ARE HACKERS"
<BR>
<BR>

<DIV ALIGN="right">
<SPAN CLASS="blinky">Proxykillah - 2000</SPAN>
</DIV>

</FONT></I></P>
</TD></TR></TABLE>
</TD></TR></TABLE>

<FONT CLASS="small" FACE="Arial"><BR>
</FONT> <!----------------3333333333333333333333333------------------> 

<TABLE BGCOLOR="#1c1f22" BORDER="0" CELLPADDING="0" CELLSPACING="1" WIDTH="100%">
<TR BGCOLOR="#515468">
<TD BGCOLOR="#024070">
<CENTER CLASS="small_uppercase"><SPAN CLASS="small"><FONT COLOR="#80899f" FACE="Arial"><B>.</B></FONT> <B><FONT COLOR="#b1b6c5" FACE="Arial">:</FONT> <FONT FACE="Arial"><FONT COLOR="#ffffff">: N
<FONT COLOR="#b1b6c5">·</FONT> E <FONT COLOR="#b1b6c5">·</FONT> W <FONT COLOR="#b1b6c5">·</FONT> S ·&nbsp;&nbsp; <FONT COLOR="#b1b6c5">·</FONT> B <FONT COLOR= 
"#B1B6C5">·</FONT> U <FONT COLOR="#b1b6c5">·</FONT> L <FONT COLOR="#b1b6c5">·</FONT> L <FONT COLOR="#b1b6c5">·</FONT> E <FONT COLOR="#b1b6c5">·</FONT> T <FONT
COLOR="#b1b6c5">·</FONT> I <FONT COLOR="#b1b6c5">·</FONT> N :</FONT> <FONT COLOR="#b1b6c5">: <FONT COLOR="#80899f">.</FONT></FONT></FONT></B></SPAN></CENTER>
</TD>
</TR>

<TR BGCOLOR="#24252f"><TD>
<TABLE BORDER="0" CELLPADDING="4" CELLSPACING="0" WIDTH="100%">
<TR><TD BGCOLOR="#1C1F22">

<center>


news here

</TD></TR></TABLE>
</TD></TR></TABLE>



<TD BGCOLOR="#000000" VALIGN="top" WIDTH="160">
<!----------------eend top------------>
<!------------left column--------------->
<TABLE BGCOLOR="#1c1f22" BORDER="0" CELLPADDING="2" CELLSPACING="1" WIDTH="160">
<TR BGCOLOR="#515468">
<TD BGCOLOR="#024070" WIDTH="160">
<CENTER>
<CENTER CLASS="small_uppercase">O T H E R</CENTER>
</CENTER>
</TD>
</TR>

<TR BGCOLOR="#1c1f22">
<TD WIDTH="160" BGCOLOR="#1c1f22" CELLPADDING="2">
<TABLE BORDER="0" CELLPADDING="4" CELLSPACING="0" WIDTH="100%">
<TR CLASS="small">
<TD BGCOLOR="#1C1F22" HEIGHT="426" VALIGN="top">
<!------menu here----------->
<CENTER>
    <?php require('menu2.php'); ?>
</center>

</TD></TR></TABLE>
</TD></TR></TABLE>

</TD></TR></TABLE>
</TD></TR></TABLE>


<TABLE BGCOLOR="#000000" BORDER="0" CELLPADDING="0" CELLSPACING="0" WIDTH="750" HEIGHT="2">
<TR BGCOLOR="#024070" HEIGHT="2"><TD BGCOLOR="#024070" HEIGHT="2"></TD></TR></TABLE>

    <?php require('footer.php'); ?>

</BODY>
</HTML>

