<form ACTION="/phpBB/login.php" METHOD="POST">
  <p><font face="Verdana" size="2" color="white"><b><font size="1">Username:</font></b></font> 
    <br>
    <input type="TEXT" name="user" size="12" maxlength="40" value="">
    <br>
    <font face="Verdana" color="white"><b><font size="1">Password: </font></b></font> 
    <br>
    <input type="PASSWORD" name="passwd" size="12" maxlength="25">
    <br>
    <input type=submit value=Submit>
  </p>
  </form>
