<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
<style type=text/css>
BODY {background-image: url(images/top.jpg); background-repeat: no-repeat;}
A:hover{ text-decoration: none; color: #FF200E; }
</style>
<title>[ nemohackers ]</title>
<LINK REL=stylesheet TYPE="text/css" HREF="style.css" TITLE="syle">
<script>
function NoError() {
return(true);
} 
onerror=NoError; 
</script>
</head>
<BODY bgcolor="#000032" bottomMargin=0 leftMargin=0 rightMargin=0
text="#FFFFFF" topMargin=0 marginheight="0" marginwidth="0" link="#2564c4" vlink="#2564c4">

<!-----image / header---------->
<table height="57"><tr><td></td></tr></table>

<table bgColor="#ffffff" height="2" width="100%" cellpadding="0" cellspacing="0">
<tr><td></td></tr></table>

<table bgColor="#000032" width="100%" cellpadding="5" cellspacing="0"><tr>
<td align="left">

<font face="Verdana, Helvetica" size=1>
<SCRIPT LANGUAGE="JavaScript">
<!-- Begin
today=new Date();
day=today.getDate();
month=today.getMonth()+1;
mydate = new Date();
mydayy = mydate.getDay();
if(mydayy == 0) dayy = " Sunday, ";
else if(mydayy == 1) dayy = " Monday, ";
else if(mydayy == 2) dayy = " Tuesday, ";
else if(mydayy == 3) dayy = " Wednesday, ";
else if(mydayy == 4) dayy = " Thurday, ";
else if(mydayy == 5) dayy = " Friday, ";
else if(mydayy == 6) dayy = " Saturday, ";
if (day==1) end=("st");
else if (day==2) end=("nd");
else if (day==3) end=("rd");
else if (day==21) end=("st");
else if (day==22) end=("nd");
else if (day==23) end=("rd");
else if (day==31) end=("st");
else end=("th");
if (month==1) name=("January");
else if (month==2) name=("February");
else if (month==3) name=("March");
else if (month==4) name=("April");
else if (month==5) name=("May");
else if (month==6) name=("June");
else if (month==7) name=("July");
else if (month==8) name=("August");
else if (month==9) name=("September");
else if (month==10) name=("October");
else if (month==11) name=("November");
else name=("December");
document.write("&nbsp;&nbsp;" + dayy + name + " " +day + end + ", " + today.getYear());
// End -->
</script>

</td>
<td align="right"><?php require("../site/includes/menu.txt");?></td></tr></table>

<table bgColor="#ffffff" height="2" width="100%" cellpadding="0" cellspacing="0">
<tr><td></td></tr></table>
<br>

<!--------main table-------------------->
<table bgcolor="#003366" width="100%" cellpadding="0" cellspacing="0"><tr>
<td width="10" bgColor="#000032"><font color="#000032">.</font></td><td>
<font color="#000032">.</font>
</td><td width="10" bgColor="#000032"><font color="#000032">.</font></td>
</tr></table>

<table border="0" cellpadding="0" cellspacing="0" width="100%"><tr valign="top">
<td width="10" bgColor="#000032"><font color="#000032">.</font></td>
<td width="10" bgcolor="#003366"><font color="#003366">.</font></td>
<td width="*" bgcolor="#ffffff"><center>

<table border="1" bgcolor="#000033" cellpadding="5" cellspacing="0" width="100%"><tr valign="top">
<td>

