<LINK REL=stylesheet TYPE="text/css" HREF="style.css" TITLE="syle">
<script>
function NoError() {
return(true);
} 
onerror=NoError; 
</script>
</HEAD>
<BODY BACKGROUND="http://nemo.r-fx.org/images/back1.gif" ALINK="#ccff00" BGCOLOR="#121212" LINK="#828fb0" TEXT="#DDDDDD" VLINK="#828fb0">

<BR>
<CENTER>
<!--------top------------->
<TABLE BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=750 HEIGHT=5>
<TR BGCOLOR="#024070" HEIGHT=5>
<TD HEIGHT=5><!---links here ---->
<CENTER>
"Their admins assumption may be the mother of all mistakes..."</TD></TR></TABLE>


<TABLE BGCOLOR=#000000 BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=750><TR>
<TD WIDTH="*" bgcolor="#0a527a">
<a href="http://nemo.r-fx.org/index.php" alt="Nemohackers.com" border=0><img border=0 src="http://nemo.r-fx.org/images/logonemo1.gif"></a>

</TD>
</TR></TABLE>



<TABLE BGCOLOR=#000000 BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=750 HEIGHT=2>
<TR BGCOLOR="#024070" HEIGHT=2><TD BGCOLOR="#024070" HEIGHT=2></TD></TR></TABLE> 

<TABLE BGCOLOR=#000000 BORDER=0 CELLPADDING=0 CELLSPACING=0 WIDTH=750><TR><TD>
<FONT CLASS="upper" COLOR="#cdcddc" FACE="Verdana" SIZE="1"><B>
&nbsp;Knowledge and Infomation will set you free<BR>
&nbsp;
/<a href="index.php">home&nbsp;</a>
<a href="<?php echo $SCRIPT_NAME; ?>"><?php echo $SCRIPT_NAME; ?></a>&nbsp;


