
image1 = new Image();
image1.src = "image1.gif";

image2 = new Image();
image2.src = "images/home_over.jpg";

image3 = new Image();
image3.src = "images/2_over.jpg";

image4 = new Image();
image4.src = "images/1_over.jpg";

image5 = new Image();
image5.src = "images/end_over.jpg";

image6 = new Image();
image6.src = "images/back_over.jpg";

image7 = new Image();
image7.src = "images/forward_over.jpg";

function over(){
document.home.src="images/home_over.jpg"
		}
function over1(){	
document.learn.src="images/1_over.jpg"
		}	
function over2(){
document.com.src="images/2_over.jpg"
		}
function over3(){
document.txts.src="images/end_over.jpg"
		}
function over4(){
document.back.src="images/back_over.jpg"
		}
function over5(){
document.forward.src="images/forward_over.jpg"
		}
		
function out(){
document.home.src="images/home.jpg"
document.learn.src="images/1.jpg"
document.com.src="images/2.jpg"
document.txts.src="images/end.jpg"
document.back.src="images/back.jpg"
document.forward.src="images/forward.jpg"
}

